osx_image: xcode9
language: objective-c

before_install:
- travis_wait 35; cd Example; pod update

script:
- xcodebuild build -workspace Blitz.xcworkspace -scheme "Blitz-Example" -sdk iphonesimulator | xcpretty

notifications:
  email: false